version: '2.0'

services:
  fms-tp:
    container_name: fms-tp
    build:
      context: .
      dockerfile: ./fms-tp/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator
    volumes:
      - '.:/project/fms'
  # web-app: # The name of the service
  #   container_name: web-app
  #   depends_on:
  #     - sawtooth-rest-api
  #   build:
  #     context: .
  #     dockerfile: ./fmsui/Dockerfile
  #   volumes:
  #     - '.:/project/fms'
  #   expose:
  #     - 4200
  #   ports:
  #     - '4200:4200'
  # web-app:
  #   container_name: web-app
  #   depends_on:
  #     - sawtooth-rest-api
  #   expose:
  #     - 4200
  #   ports:
  #     - 4200:4200
  #   build:
  #     context: .
  #     dockerfile: ./fmsui/Dockerfile
  # web-app:
  #   container_name: web-app
  #   depends_on:
  #     - sawtooth-rest-api
  #   expose:
  #     - 3000
  #   ports:
  #     - 3000:3000
  # build:
  #   context: .
  #   dockerfile: ./fmsui/Dockerfile
  #     args:
  #       - http_proxy
  #       - https_proxy
  #       - no_proxy
  #   volumes:
  #     - '.:/project/fms'

  sawtooth-rest-api:
    container_name: rest-api
    image: hyperledger/sawtooth-rest-api:1.0
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vvv
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008

  settings-tp:
    container_name: settings
    image: hyperledger/sawtooth-settings-tp:1.0
    depends_on:
      - validator
    command: settings-tp -vv --connect tcp://validator:4004

  validator:
    container_name: validator
    image: hyperledger/sawtooth-validator:1.0
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vvv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
